import { useState } from 'react'
import Head from 'next/head'
import Box from '@mui/material/Box'
import InputLabel from '@mui/material/InputLabel'
import MenuItem from '@mui/material/MenuItem'
import FormControl from '@mui/material/FormControl'
import Select from '@mui/material/Select'
import TextField from '@mui/material/TextField'
import ReportCard from '../components/ReportCard'
import reportsData from '../data/reports.json'

export default function Reports () {
  const [contratacion, setcontratacion] = useState('Seleccionar todo')
  const [query, setQuery] = useState('')
  const types = [...new Set(reportsData.map(item => item.type))]

  console.log(query)

  const handleChange = (event) => {
    setcontratacion(event.target.value)
  }

  const handleQueryChange = (event) => {
    setQuery(event.target.value)
  }

  const filteredData = contratacion !== 'Seleccionar todo' ? reportsData.filter(item => item.type === contratacion).filter(item => item.title.toLowerCase().includes(query.toLowerCase())) : reportsData.filter(item => item.title.toLowerCase().includes(query.toLowerCase()))

  return (
    <>
      <Head>
        <title>Informes | Banderas Ecuador</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='py-12 lg:py-16 xl:py-20'>
        <div className='mx-auto w-10/12 max-w-screen-2xl'>
          <div className='space-y-8'>
            <div className='max-w-[440px] mx-auto text-center'>
              <h1 className='inline-block font-black text-5xl 3xl:text-[65px]'>
                <span>Informes</span>
                <div className='-mt-3 bg-orange-red bg-opacity-[0.4] h-[23px] w-full'>&nbsp;</div>
              </h1>
              <p>
                En esta sección te compartimos nuestras nuevas publicaciones e informes de investigación
              </p>
            </div>
            <div className='flex flex-col lg:flex-row lg:justify-between items-center gap-y-8'>
              <div className='max-w-[400px] w-full'>
                <div className='space-y-[11px]'>
                  <p className='block font-black 3xl:text-[19px]'>
                    Filtros
                  </p>
                  <Box sx={{ minWidth: 120 }}>
                    <FormControl fullWidth>
                      <InputLabel id="demo-simple-select-label">Contratación</InputLabel>
                      <Select
                        labelId="demo-simple-select-label"
                        id="demo-simple-select"
                        value={contratacion}
                        label="Contratación"
                        onChange={handleChange}
                        className="bg-white"
                      >
                        <MenuItem value="Seleccionar todo">Seleccionar todo</MenuItem>
                        {
                          types.map((item, idx) => <MenuItem key={`report-filter-${idx + 1}`} value={item}>{item}</MenuItem>)
                        }
                      </Select>
                    </FormControl>
                  </Box>
                </div>
              </div>
              <div className='max-w-[400px] w-full'>
                <div className='space-y-[11px]'>
                  <p className='block font-black 3xl:text-[19px]'>
                    Búsqueda
                  </p>
                  <Box
                    component="form"
                    sx={{
                      '& > :not(style)': { m: 1, width: '100%' }
                    }}
                    noValidate
                    autoComplete="off"
                  >
                    <TextField onChange={handleQueryChange} fullWidth id="outlined-basic" label="Buscar" variant="outlined" />
                  </Box>
                </div>
              </div>
            </div>
            <div className='grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-[83px] gap-y-[45px]'>
              {
                filteredData.length > 0
                  ? filteredData.map(({ id, srcImage, title, date, link }) => <ReportCard key={`report-${id + 1}`} id={id} srcImage={srcImage} title={title} date={date} link={link} />)
                  : <div>No hay resultados</div>
              }
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
