import React from 'react'
import Head from 'next/head'
import Box from '@mui/material/Box'
import InputLabel from '@mui/material/InputLabel'
import MenuItem from '@mui/material/MenuItem'
import FormControl from '@mui/material/FormControl'
import Select from '@mui/material/Select'
import TextField from '@mui/material/TextField'

export default function reports () {
  const [contratacion, setcontratacion] = React.useState('')

  const handleChange = (event) => {
    setcontratacion(event.target.value)
  }
  return (
    <>
      <Head>
        <title>Informes | Banderas Ecuador</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='py-12 lg:py-16 xl:py-20'>
        <div className='mx-auto w-10/12 max-w-screen-2xl'>
          <div className='space-y-8'>
            <div className='max-w-[440px] mx-auto text-center'>
              <h1 className='inline-block font-black text-5xl 3xl:text-[65px]'>
                <span>Informes</span>
                <div className='-mt-3 bg-orange-red bg-opacity-[0.4] h-[23px] w-full'>&nbsp;</div>
              </h1>
              <p>
                En esta sección te compartimos nuestras nuevas publicaciones e informes de investigación
              </p>
            </div>
            <div className='flex flex-col lg:flex-row lg:justify-between items-center gap-y-8'>
              <div className='max-w-[400px] w-full'>
                <div className='space-y-[11px]'>
                  <p className='block font-black 3xl:text-[19px]'>
                    Filtros
                  </p>
                  <Box sx={{ minWidth: 120 }}>
                    <FormControl fullWidth>
                      <InputLabel id="demo-simple-select-label">Contratación</InputLabel>
                      <Select
                        labelId="demo-simple-select-label"
                        id="demo-simple-select"
                        value={contratacion}
                        label="Contratación"
                        onChange={handleChange}
                        className="bg-white"
                      >
                        <MenuItem value="Contratación por emergencia">Contratación por emergencia</MenuItem>
                      </Select>
                    </FormControl>
                  </Box>
                </div>
              </div>
              <div className='max-w-[400px] w-full'>
                <div className='space-y-[11px]'>
                  <p className='block font-black 3xl:text-[19px]'>
                    Busqueda
                  </p>
                  <Box
                    component="form"
                    sx={{
                      '& > :not(style)': { m: 1, width: '100%' }
                    }}
                    noValidate
                    autoComplete="off"
                  >
                    <TextField fullWidth id="outlined-basic" label="Buscar" variant="outlined" />
                  </Box>
                </div>
              </div>
            </div>
            <div className='grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3'>
              <div className='bg-white rounded-[30px] pt-[42px] pb-[25px] px-[50px] flex flex-col justify-between space-y-6 hover:shadow-3 duration-300'>
                <div>
                  <img src="/informe-1.jpg" alt="informe 1" />
                  <h3 className='font-medium 3xl:text-[21px] mt-[27.93px]'>
                    Compra Pública Corporativa de Medicamentos
                  </h3>
                  <p className='text-grey-light italic 3xl:text-[19px] mt-[10.32px]'>
                    Publicado el 7 de junio de 2022
                  </p>
                </div>
                <div>
                  <a className='inline-block bg-red text-white py-[10px] px-[40px] font-bold rounded-[15px]' href="#">
                    <span>Descargar</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
